import { SearchHiraModel } from '../model/bank-response.model';

export const listHiraBank: SearchHiraModel[] = [
  {key_hira: 'あ', key_kata: 'ｱ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'か', key_kata: 'ｶ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'さ', key_kata: 'ｻ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'た', key_kata: 'ﾀ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'な', key_kata: 'ﾅ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'は', key_kata: 'ﾊ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'ま', key_kata: 'ﾏ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'や', key_kata: 'ﾔ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'ら', key_kata: 'ｻ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'わ', key_kata: 'ﾜ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'い', key_kata: 'ｲ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'き', key_kata: 'ｷ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'し', key_kata: 'ｼ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'ち', key_kata: 'ﾁ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'に', key_kata: 'ﾆ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'ひ', key_kata: 'ﾋ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'み', key_kata: 'ﾐ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: ' ', key_kata: ' ', class: 'btn-none'},
  {key_hira: 'り', key_kata: 'ﾘ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: ' ', key_kata: ' ', class: 'btn-none'},
  {key_hira: 'う', key_kata: 'ｳ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'く', key_kata: 'ｸ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'す', key_kata: 'ｽ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'つ', key_kata: 'ﾂ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'ぬ', key_kata: 'ﾇ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'ふ', key_kata: 'ﾌ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'む', key_kata: 'ﾑ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'ゆ', key_kata: 'ﾕ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'る', key_kata: 'ﾙ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'を', key_kata: 'ｦ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'え', key_kata: 'ｴ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'け', key_kata: 'ｹ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'せ', key_kata: 'ｾ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'て', key_kata: 'ﾃ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'ね', key_kata: 'ﾈ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'へ', key_kata: 'ﾍ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'め', key_kata: 'ﾒ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: ' ', key_kata: ' ', class: 'btn-none'},
  {key_hira: 'れ', key_kata: 'ﾚ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: ' ', key_kata: ' ', class: 'btn-none'},
  {key_hira: 'こ', key_kata: 'ｺ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'そ', key_kata: 'ｿ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'と', key_kata: 'ﾄ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'の', key_kata: 'ﾉ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'ほ', key_kata: 'ﾎ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'も', key_kata: 'ﾓ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'よ', key_kata: 'ﾖ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'ろ', key_kata: 'ﾛ', class: 'btn btn-sm btn-character disabled'},
  {key_hira: 'ん', key_kata: 'ﾝ', class: 'btn btn-sm btn-character disabled'}
  ];
export const listHiraBranch: SearchHiraModel[] = [
    {key_hira: 'あ', key_kata: 'ｱ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'か', key_kata: 'ｶ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'さ', key_kata: 'ｻ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'た', key_kata: 'ﾀ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'な', key_kata: 'ﾅ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'は', key_kata: 'ﾊ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'ま', key_kata: 'ﾏ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'や', key_kata: 'ﾔ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'ら', key_kata: 'ｻ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'わ', key_kata: 'ﾜ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'い', key_kata: 'ｲ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'き', key_kata: 'ｷ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'し', key_kata: 'ｼ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'ち', key_kata: 'ﾁ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'に', key_kata: 'ﾆ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'ひ', key_kata: 'ﾋ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'み', key_kata: 'ﾐ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: ' ', key_kata: ' ', class: 'btn-none'},
    {key_hira: 'り', key_kata: 'ﾘ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: ' ', key_kata: ' ', class: 'btn-none'},
    {key_hira: 'う', key_kata: 'ｳ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'く', key_kata: 'ｸ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'す', key_kata: 'ｽ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'つ', key_kata: 'ﾂ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'ぬ', key_kata: 'ﾇ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'ふ', key_kata: 'ﾌ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'む', key_kata: 'ﾑ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'ゆ', key_kata: 'ﾕ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'る', key_kata: 'ﾙ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'を', key_kata: 'ｦ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'え', key_kata: 'ｴ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'け', key_kata: 'ｹ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'せ', key_kata: 'ｾ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'て', key_kata: 'ﾃ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'ね', key_kata: 'ﾈ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'へ', key_kata: 'ﾍ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'め', key_kata: 'ﾒ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: ' ', key_kata: ' ', class: 'btn-none'},
    {key_hira: 'れ', key_kata: 'ﾚ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: ' ', key_kata: ' ', class: 'btn-none'},
    {key_hira: 'こ', key_kata: 'ｺ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'そ', key_kata: 'ｿ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'と', key_kata: 'ﾄ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'の', key_kata: 'ﾉ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'ほ', key_kata: 'ﾎ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'も', key_kata: 'ﾓ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'よ', key_kata: 'ﾖ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'ろ', key_kata: 'ﾛ', class: 'btn btn-sm btn-character disabled'},
    {key_hira: 'ん', key_kata: 'ﾝ', class: 'btn btn-sm btn-character disabled'}
    ];
